import React from 'react'
import Head from 'next/head'
 const Department=()=>{

    return (
        <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

<section class="page-title-section bg-img cover-background theme-overlay" data-overlay-dark="7" data-background="img/bg/bg-07.jpg">
            <div class="container">

                <div class="row">
                    <div class="col-md-12">
                        <h1>Cardiology</h1>
                    </div>
                    <div class="col-md-12">
                        <ul>
                            <li><a href="home-1.html">Home</a></li>
                            <li class="active"><a href="#!">Cardiology</a></li>
                        </ul>
                    </div>
                </div>

            </div>
        </section>

    

        <section>
            <div class="container">
                <div class="row">

                
                    <div class="col-lg-3 col-md-12">
                        <div class="categories mb-4">
                            <h3 class="bg-primary text-white m-0 h5 px-4 py-3 font-weight-600 d-none d-lg-block">Departments</h3>
                            <h3 class="bg-primary text-white collapse-sm m-0 h5 px-4 py-3 font-weight-600 d-lg-none d-block">Departments</h3>
                            <ul class="list-style1 dept-category box-shadow-large m-0">
                                <li><a href="cardiology.html">Cardiology</a></li>
                                <li><a href="gynecology.html">Gynecology</a></li>
                                <li><a href="neurology.html">Neurology</a></li>
                                <li><a href="orthopedics.html">Orthopedics</a></li>
                                <li><a href="pulmonology.html">Pulmonology</a></li>
                                <li><a href="gastrology.html">Gastrology</a></li>
                                <li><a href="urology.html">Urology</a></li>
                                <li><a href="laboratory.html">Laboratory</a></li>
                            </ul>
                        </div>
                        <div class="mb-4 d-none d-lg-block">
                            <h3 class="bg-primary text-white m-0 h5 px-4 py-3 font-weight-600 d-none d-lg-block">Opening Hours</h3>
                            <ul class="list-style1 dept-category box-shadow-large no-margin">
                                <li>Mon to Fri: 09.00 to 18.00</li>
                                <li>Saturday: 10.00 to 16.00</li>
                                <li>Sunday: 10.00 to 14.00</li>
                            </ul>
                        </div>
                        <div class="d-none d-lg-block">
                            <h3 class="bg-primary text-white m-0 h5 px-4 py-3 font-weight-600 d-none d-lg-block">Quick Contact</h3>
                            <ul class="list-style1 no-list-style box-shadow-large m-0">
                                <li>
                                    <span class="d-inline-block align-top size18"><i class="fas fa-phone text-primary"></i></span>
                                    <span class="d-inline-block align-top pl-2">(+44) 123 456 789</span>
                                </li>
                                <li>
                                    <span class="d-inline-block align-top"><i class="far fa-envelope text-primary"></i></span>
                                    <span class="d-inline-block align-top pl-2">addyour@emailhere</span>
                                </li>
                            </ul>
                        </div>
                    </div>
            

                    <div class="col-lg-9 col-md-12">
                        <div class="department-details pl-lg-4">
                            <div class="owl-carousel owl-theme mb-2-0 mb-lg-5">
                                <div class="item">
                                    <div class="border border-width-10"><img alt="img" src="img/content/department-01.jpg" /></div>
                                </div>
                                <div class="item">
                                    <div class="border border-width-10"><img alt="img" src="img/content/department-02.jpg" /></div>
                                </div>
                                <div class="item">
                                    <div class="border border-width-10"><img alt="img" src="img/content/department-03.jpg" /></div>
                                </div>
                            </div>
                            <h3 class="mb-4 h4">Cardiology</h3>
                            <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur.</p>
                            <p class="m-0">Xcepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error.</p>

                            <div class="separator-line-horrizontal-full bg-extra-light-gray mx-auto mt-2-4 mb-5"></div>

                            <div class="row">
                                <div class="col-12">
                                    <h3 class="mb-4 h4">Meet the Experts</h3>
                                </div>
                                <div class="col-lg-4 col-md-6 col-sm-6 text-center mb-1-9 mb-lg-0">
                                    <div class="team-style">
                                        <div class="team-member-img mb-4">
                                            <img alt="" src="img/team/team-01.jpg" class="img-responsive"/>
                                            <div class="team-description">
                                                <div class="team-description-wrapper">

                                                    <div class="team-description-content">
                                                        <div class="social-links">
                                                            <a href="#!" class="d-inline-block mr-2"><i class="fab fa-facebook-f text-white"></i></a>
                                                            <a href="#!" class="d-inline-block mr-2"><i class="fab fa-twitter text-white"></i></a>
                                                            <a href="#!" class="d-inline-block mr-2"><i class="fab fa-linkedin-in text-white"></i></a>
                                                            <a href="#!" class="d-inline-block"><i class="fab fa-instagram text-white"></i></a>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="text-center">
                                            <h5 class="text-muted h6 mb-1 font-weight-600"><a href="team-single.html">Jama Karle</a></h5>
                                            <span>Master of Surgery</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-4 col-md-6 col-sm-6 text-center mb-1-9 mb-lg-0">
                                    <div class="team-style">
                                        <div class="team-member-img mb-4">
                                            <img alt="" src="img/team/team-02.jpg" class="img-responsive"/>
                                            <div class="team-description">
                                                <div class="team-description-wrapper">

                                                    <div class="team-description-content">
                                                        <div class="social-links">
                                                            <a href="#!" class="d-inline-block mr-2"><i class="fab fa-facebook-f text-white"></i></a>
                                                            <a href="#!" class="d-inline-block mr-2"><i class="fab fa-twitter text-white"></i></a>
                                                            <a href="#!" class="d-inline-block mr-2"><i class="fab fa-linkedin-in text-white"></i></a>
                                                            <a href="#!" class="d-inline-block"><i class="fab fa-instagram text-white"></i></a>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="text-center">
                                            <h5 class="text-muted h6 mb-1 font-weight-600"><a href="team-single.html">Keir Prestonly</a></h5>
                                            <span class="font-size14">Osteopathic Medicine</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-4 col-md-6 col-sm-6 text-center">
                                    <div class="team-style">
                                        <div class="team-member-img mb-4">
                                            <img alt="" src="img/team/team-03.jpg" class="img-responsive"/>
                                            <div class="team-description">
                                                <div class="team-description-wrapper">

                                                    <div class="team-description-content">
                                                        <div class="social-links">
                                                            <a href="#!" class="d-inline-block mr-2"><i class="fab fa-facebook-f text-white"></i></a>
                                                            <a href="#!" class="d-inline-block mr-2"><i class="fab fa-twitter text-white"></i></a>
                                                            <a href="#!" class="d-inline-block mr-2"><i class="fab fa-linkedin-in text-white"></i></a>
                                                            <a href="#!" class="d-inline-block"><i class="fab fa-instagram text-white"></i></a>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="text-center">
                                            <h5 class="text-muted h6 mb-1 font-weight-600"><a href="team-single.html">Finley Walkeror</a></h5>
                                            <span>MD PhD</span>
                                        </div>
                                    </div>
                                </div>

                            </div>

                            <div class="separator-line-horrizontal-full bg-extra-light-gray mx-auto mt-2-4 mb-5"></div>

                            <div class="row">
                                <div class="col-12">
                                    <h3 class="mb-4 h4">Book Appointment</h3>
                                </div>
                                <div class="col-12">
                                    <form class="quform" action="quform/book-appointment.php" method="post" enctype="multipart/form-data" onclick="">
                                        <div class="quform-elements">

                                            <div class="row">

                                        
                                                <div class="col-sm-6">
                                                    <div class="quform-element form-group">
                                                        <div class="quform-input">
                                                            <input class="form-control" id="name" type="text" name="name" placeholder="First Name" />
                                                        </div>
                                                    </div>

                                                </div>
                                

                                
                                                <div class="col-sm-6">
                                                    <div class="quform-element form-group">
                                                        <div class="quform-input">
                                                            <input class="form-control" id="last_name" type="text" name="last_name" placeholder="Last Name" />
                                                        </div>
                                                    </div>
                                                </div>
                                            

                                
                                                <div class="col-sm-6">
                                                    <div class="quform-element form-group">
                                                        <div class="quform-input">
                                                            <input class="form-control" id="phone" type="text" name="phone" placeholder="Your phone number" />
                                                        </div>
                                                    </div>

                                                </div>
                                            

                                    
                                                <div class="col-sm-6">
                                                    <div class="quform-element form-group">
                                                        <div class="quform-input">
                                                            <input class="form-control" id="email" type="text" name="email" placeholder="Your email" />
                                                        </div>
                                                    </div>
                                                </div>
                                                

                                        
                                                <div class="col-sm-6">
                                                    <div class="quform-element form-group">
                                                        <div class="quform-input">
                                                            <input class="form-control date form_date" data-date-format="dd MM yyyy" data-link-format="yyyy-mm-dd" size="16" type="text" id="date" name="date" value="" placeholder="Appoinment date"/>
                                                        </div>
                                                    </div>
                                                </div>
                                            

                                        
                                                <div class="col-sm-6">
                                                    <div class="quform-element form-group">
                                                        <div class="quform-input">
                                                            <input class="form-control date form_time" data-date="" data-date-format="hh:ii" data-link-format="hh:ii" size="16" type="text" id="time" name="time" value="" placeholder="Appoinment time"/>
                                                        </div>
                                                    </div>
                                                </div>
                                        

                                
                                                <div class="col-sm-6">
                                                    <div class="quform-element form-group">
                                                        <div class="quform-input">
                                                            <select class="form-control form-select" id="department" name="department">
                                                                <option value="">-- Select Department --</option>
                                                                <option value="Cardiology">Cardiology</option>
                                                                <option value="Gynecology">Gynecology</option>
                                                                <option value="Neurology">Neurology</option>
                                                                <option value="Orthopedics">Orthopedics</option>
                                                                <option value="Pulmonology">Pulmonology</option>
                                                                <option value="Gastrology">Gastrology</option>
                                                                <option value="Urology">Urology</option>
                                                                <option value="Laboratory">Laboratory</option>
                                                                <option value="Others">Others</option>
                                                            </select>
                                                        </div>
                                                    </div>

                                                </div>
                                                

                                            
                                                <div class="col-sm-6">
                                                    <div class="quform-element form-group">
                                                        <div class="quform-input">
                                                            <select class="form-control form-select" id="doctors" name="doctors">
                                                                <option value="">-- Choose Your Doctor --</option>
                                                                <option value="Jama Karle">Jama Karle</option>
                                                                <option value="Keir Prestonly">Keir Prestonly</option>
                                                                <option value="Finley Walkeror">Finley Walkeror</option>
                                                                <option value="Dont know">Dont know</option>
                                                            </select>
                                                        </div>
                                                    </div>

                                                </div>
                                            

                                            
                                                <div class="col-md-12">
                                                    <div class="quform-element form-group">

                                                        
                                                        <div class="quform-input">

                                                            <div class="custom-file">
                                                                <input class="custom-file-input" type="file" id="files" name="files" />
                                                                <label class="custom-file-label" data-browse="Browse">Choose file</label>
                                                            </div>

                                                            <p class="quform-description">All files allowed. Maximum size 10MB.</p>

                                                        </div>
                                                    

                                                    </div>

                                                </div>
                                                

                                            
                                                <div class="col-md-12">
                                                    <div class="quform-element form-group">
                                                        <div class="quform-input">
                                                            <textarea class="form-control" id="message" name="message" rows="3" placeholder="Message"></textarea>
                                                        </div>
                                                    </div>
                                                </div>
                                        

                                            
                                                <div class="col-md-12">
                                                    <div class="quform-element">
                                                        <div class="form-group">
                                                            <div class="quform-input">
                                                                <input class="form-control" id="type_the_word" type="text" name="type_the_word" placeholder="Type the below word" />
                                                            </div>
                                                        </div>
                                                        <div class="form-group">
                                                            <div class="quform-captcha">
                                                                <div class="quform-captcha-inner">
                                                                    <img src="quform/images/captcha/courier-new-light.png" alt="..."/>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                        

                                    
                                                <div class="col-md-12">
                                                    <div class="quform-submit-inner text-center">
                                                        <button class="butn w-100" type="submit"><span>Submit Now</span></button>
                                                    </div>
                                                    <div class="quform-loading-wrap"><span class="quform-loading"></span></div>
                                                </div>
                                

                                            </div>

                                        </div>
                                    </form>
                                </div>
                            </div>

                        </div>
                    </div>

                </div>
            </div>
        </section>
        </>
    )
 }
export default Department;