import React from 'react'
import Head from 'next/head'
const Doctor=()=>{
    return(
        <>
         <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
          <section>
            <div className="container">
                <div className="row">
                    <div className="col-md-6 col-lg-4 mb-2-9 mb-lg-0">
                        <div className="team-style2">
                            <img src="/img/team/team-13.jpg" alt="..." className="rounded-top"/>
                            <div className="bg-white team-text py-4 position-relative">
                                <ul className="team-social">
                                    <li>
                                        <a href="#!"><i className="fab fa-facebook-f"></i></a>
                                    </li>
                                    <li>
                                        <a href="#!"><i className="fab fa-twitter"></i></a>
                                    </li>
                                    <li>
                                        <a href="#!"><i className="fab fa-instagram"></i></a>
                                    </li>
                                </ul>
                                <h3 className="h6 mb-1">DR. Janet Daniels</h3>
                                <span className="font-weight-600 small text-uppercase text-primary">Periodontics</span>
                            </div>
                        </div>
                    </div>
                    <div className="col-md-6 col-lg-4 mb-2-9 mb-lg-0">
                        <div className="team-style2">
                            <img src="/img/team/team-14.jpg" alt="..." className="rounded-top"/>
                            <div className="bg-white team-text py-4 position-relative">
                                <ul className="team-social">
                                    <li>
                                        <a href="#!"><i className="fab fa-facebook-f"></i></a>
                                    </li>
                                    <li>
                                        <a href="#!"><i className="fab fa-twitter"></i></a>
                                    </li>
                                    <li>
                                        <a href="#!"><i className="fab fa-instagram"></i></a>
                                    </li>
                                </ul>
                                <h3 className="h6 mb-1">DR. George Lafortune</h3>
                                <span className="font-weight-600 small text-uppercase text-primary">Orthodontics</span>
                            </div>
                        </div>
                    </div>
                    <div className="col-md-6 col-lg-4">
                        <div className="team-style2">
                            <img src="/img/team/team-15.jpg" alt="..." className="rounded-top"/>
                            <div className="bg-white team-text py-4 position-relative">
                                <ul className="team-social">
                                    <li>
                                        <a href="#!"><i className="fab fa-facebook-f"></i></a>
                                    </li>
                                    <li>
                                        <a href="#!"><i className="fab fa-twitter"></i></a>
                                    </li>
                                    <li>
                                        <a href="#!"><i className="fab fa-instagram"></i></a>
                                    </li>
                                </ul>
                                <h3 className="h6 mb-1">DR. John Lee</h3>
                                <span className="font-weight-600 small text-uppercase text-primary">Oral Medicine and radiology</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        </>
    )
}

export default Doctor;