import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import MainSlider from '../components/MainSlider'
import About from '../components/About'
import Services from '../components/Services'
import Department from '../components/Department'
import AppointmentComponent from '../components/AppointmentComponent'
import Counter from '../components/Counter'
import Testimonial from '../components/Testimonial'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <MainSlider />
       
      <About />
      <Services />
      <Department />
      <AppointmentComponent />
      <Counter />
      <Testimonial />
    </div>
  )
}
